name: Run every day

on:
  schedule:
    # 매일 오전 0시(UTC) = 오전 9시(KST)
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  run-python:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install system deps (Chromium & driver)
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver

      - name: Install Python packages
        run: |
          python -m pip install --upgrade pip
          pip install \
            gspread \
            oauth2client \
            selenium \
            openai \
            python-dateutil \
            webdriver-manager

      - name: Run autogit
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GCP_CREDENTIALS_JSON: ${{ secrets.GCP_CREDENTIALS_JSON }}
        run: python autogit.py
